package ru.alex;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class PostgreJdbc {
    private Connection connection;
    private Statement statement;

    public void connect(){
        String URL = "jdbc:postgresql://127.0.0.1:5432/first_db";
        String user = "postgres";
        String pas  = "12345";
        connection = PostgreConnect.returnConnection(URL,user,pas);
        try {
            statement = connection.createStatement();
            connection.setAutoCommit(false);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void InitialDb()  {
        String drop = "DROP TABLE Users;";
        String searchTable = "select * from pg_tables where tablename='users'";
        ResultSet resultSet = null;
        try {
            resultSet = statement.executeQuery(searchTable);

            if (resultSet.next()){
                statement.executeUpdate(drop);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        String createTableSQL = "CREATE TABLE USERS("
                + "ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "NAME VARCHAR(20) NOT NULL, "
                + "AGE smallint NOT NULL, "
                + "PHONE VARCHAR(20) NOT NULL,"
                + "ADDRESS VARCHAR(100))";

        try {
            statement.executeUpdate(createTableSQL);
            connection.commit();
        } catch (SQLException e) {
            try {
                connection.rollback();
            } catch (SQLException throwables) {
                throwables.printStackTrace();
            }
            e.printStackTrace();
        }

    }

    public void generateFakeUsers(){

        String generateUsers = "INSERT INTO users (name, age, phone, address)" +
        " VALUES ('%s', %o, '%s', '%s');";

        try {
            statement.addBatch(String.format(generateUsers,"Alex K",33,"333-44-212","где то далеко, горят города"));
            statement.addBatch(String.format(generateUsers,"Михаил",39,"132-19-02","где то далеко, горят города"));
            statement.addBatch(String.format(generateUsers,"Петр",23,"434-09-09","где то далеко, горят города"));
            statement.addBatch(String.format(generateUsers,"Ольга",33,"333-44-212","где то далеко, горят города"));
            statement.addBatch(String.format(generateUsers,"Света",33,"333-44-212","где то далеко, горят города"));
            statement.addBatch(String.format(generateUsers,"Сергей Р",33,"333-44-212","где то далеко, горят города"));
            statement.executeBatch();
            connection.commit();
            System.out.println("Fake users generated!!!");
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }


    }

    public void close(){
        try {
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

}
